name: Dynatrace CI - Python Docker App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  dynatrace-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Build and start containers
      run: |
        docker-compose up --build -d
        echo "Waiting for services to start..."
        sleep 20

    - name: Check if Prometheus exporter exposes metrics
      run: |
        for i in {1..5}; do
          echo "Checking exporter... attempt $i"
          if curl -s http://localhost:8000/metrics | grep bitcoin_price_usd; then
            echo "✅ Exporter is working"
            break
          fi
          sleep 5
        done
        docker-compose logs bitcoin-monitor

    - name: Run tests inside bitcoin-monitor container
      run: |
        docker-compose exec -T bitcoin-monitor pytest -v bitcoin_monitor/tests || echo "No tests found"

    - name: Lint Python code inside container
      run: |
        docker-compose exec -T bitcoin-monitor flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        docker-compose exec -T bitcoin-monitor flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Tear down containers
      if: always()
      run: docker-compose down
